game/urls.py
from django.urls import path
from . import views


app_name = 'game'

urlpatterns = [
    path('my-questions/', views.MyQuestionListView.as_view(), name='my_questions'),
    path('my-answers/', views.MyAnswersListView.as_view(), name='my_answers'),
    path('create-question-or-answer/', views.create_question_or_answer_view, 
                                       name='create_question_or_answer'),
    path('ajax-create-question/', views.ajax_create_question, name='ajax_create_question'),
    path('ajax-delete-question/<int:question_id>', views.ajax_delete_question, name='ajax_delete_question'),
    path('ajax-update-question/<int:question_id>', views.ajax_update_question, name='ajax_update_question'),
    path('ajax-create-answer/', views.ajax_create_answer, name='ajax_create_answer'),
    path('ajax-delete-answer/<int:answer_id>', views.ajax_delete_answer, name='ajax_delete_answer'),

    # колода
    path('create-deck/', views.create_deck_view, name='create_deck'),
    path('my-decks/', views.DeckListView.as_view(), name='my_decks'),
    path('ajax-create-deck/', views.ajax_create_deck, name='ajax_create_deck'),
    path('ajax-delete-deck/<int:deck_id>', views.ajax_delete_deck, name='ajax_delete_deck'),
    path('ajax-update-deck/<int:deck_id>', views.ajax_update_deck, name='ajax_update_deck'),

    # главная
    # path('',)

    # игра
    # path('play/'),
    # path('create-game/', views.create_game_view, name='create_game'),
]

memotron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('game.urls', namespace='game')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/models.py
from django.db import models
from django.core.validators import MinLengthValidator


class Question(models.Model):
    '''Модель вопроса. Вопрос - часть игры memotron'''

    user = models.ForeignKey('auth.user', 
                             on_delete=models.CASCADE, 
                             related_name='questions')
    text = models.TextField('Текст вопроса',
                             validators=[MinLengthValidator(20)])
    created = models.DateTimeField('Дата создания', 
                                    auto_now_add=True)
    updated = models.DateTimeField('Дата обновления',
                                    auto_now=True,
                                    null=True)
    is_published = models.BooleanField('Вопрос опубликован?', 
                                        default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Вопрос: "{self.text[:20]}"'


class Answer(models.Model):
    '''Модель ответа. Ответ - часть игры memotron'''

    user = models.ForeignKey('auth.user', 
                             on_delete=models.CASCADE, 
                             related_name='answers')
    image = models.ImageField('Изображение', upload_to='answer/%Y/%m/%d/')
    text = models.TextField('Текст ответа', blank=True, null=True)
    is_published = models.BooleanField('Ответ опубликован?', 
                                        default=False)
    created = models.DateTimeField('Дата создания', 
                                    auto_now_add=True)
    updated = models.DateTimeField('Дата обновления',
                                    auto_now=True,
                                    null=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Ответ "{self.id}"'


class Deck(models.Model):
    '''Колода, включающая в себя карты с вопросами и карты с ответами.'''

    user = models.ForeignKey('auth.user', on_delete=models.CASCADE,
                            related_name='decks')
    title = models.CharField('Название колоды', max_length=250)
    text = models.TextField('Описание колоды', blank=True,
                            null=True)
    image = models.ImageField('Изображение', upload_to='deck/%Y/%m/%d',
                              blank=True,
                              null=True)
    questions = models.ManyToManyField(Question, related_name='decks',
                                        verbose_name='Вопросы',
                                        blank=True)
    answers = models.ManyToManyField(Answer, related_name='decks',
                                        verbose_name='Ответы',
                                        blank=True)
    is_published = models.BooleanField('Ответ опубликован?', 
                                        default=False)
    created = models.DateTimeField('Дата создания', 
                                    auto_now_add=True)
    updated = models.DateTimeField('Дата обновления',
                                    auto_now=True,
                                    null=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_question_ids(self, template=True):
        '''Получить список id вопросов конкретной колоды.
        Если template=True, то список вернется в отформатированном для шаблона виде'''
        if template:
            return ','.join([str(q['id']) for q in self.questions.values('id')])

    def get_answer_ids(self, template=True):
        '''Получить список id ответов конкретной колоды.
        Если template=True, то список вернется в отформатированном для шаблона виде'''
        if template:
            return ','.join([str(a['id']) for a in self.answers.values('id')])



class Game(models.Model):
    '''Модель игры. Содержит некоторые данные об игре. Основные данные хранятся в Redis во время игры.'''

    user = models.ForeignKey('auth.user', on_delete=models.CASCADE,
                            related_name='games')
    players = models.ManyToManyField('auth.user', 
                                     related_name='game', 
                                     through='Membership', 
                                     verbose_name='Игроки')
    is_active = models.BooleanField('Игра запущена?', db_index=True,
                                    default=False)
    deck = models.OneToOneField(Deck, 
                                on_delete=models.CASCADE,
                                related_name='game',
                                verbose_name='Колода')
    created = models.DateTimeField('Дата создания игры', auto_now_add=True)


class Membership(models.Model):
    '''Модель для связи many-to-many User и Game, чтобы хранить дополнительные поля'''

    game = models.ForeignKey(Game, on_delete=models.CASCADE, related_name='memberships')
    user = models.ForeignKey('auth.user', on_delete=models.CASCADE, related_name='memberships')
    answers = models.IntegerField('Количество ответов всего', default=0)
    wins = models.IntegerField('Количество побед', default=0)

game/forms.py
from django import forms

from .models import Deck, Game, Question, Answer
from account.services.utils.forms import process_form_fields


class CreateQuestionForm(forms.ModelForm):
    '''Форма создания вопроса пользователем'''

    class Meta:
        model = Question
        fields = ('text', 'is_published')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        # изменение полей формы и их виджетов (например, добавление классов bootstrap)
        process_form_fields(self, checked=True)


class CreateAnswerForm(forms.ModelForm):
    '''Форма создания ответа пользователем'''

    class Meta:
        model = Answer
        fields = ['image', 'text', 'is_published']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        # изменение полей формы и их виджетов (например, добавление классов bootstrap)
        process_form_fields(self, checked=True, textarea_rows=1)


class CreateDeckForm(forms.ModelForm):
    '''Форма создания колоды'''

    class Meta:
        model = Deck
        fields = ['title', 'text', 'image', 'is_published']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        # изменение полей формы и их виджетов (например, добавление классов bootstrap)
        process_form_fields(self, checked=True, textarea_rows=1)


class CreateGameForm(forms.ModelForm):
    '''Форма создания игры'''

    players = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'type': 'search'
            }
        ),
        required=False,
        label='Игроки'
    )
    
    class Meta:
        model = Game
        fields = ('players', 'deck')

    
    def __init__(self, *args, **kwargs):
        forms.ModelForm.__init__(self, *args, *kwargs)
        process_form_fields(self)

game/views.py
from django.core.exceptions import ValidationError
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.generic import ListView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden

from account.services.utils.ajax import is_ajax
from .services import questions, answers, deck_service
from .models import Answer, Deck, Question
from .forms import CreateQuestionForm, CreateAnswerForm, CreateDeckForm


class MyQuestionListView(ListView):
    '''Список вопросов пользователя'''
    model = Question
    context_object_name = 'questions_list'
    template_name = 'question/list.html'

    def get_queryset(self):
        '''Взять только вопросы пользователя'''
        return Question.objects.filter(user__id=self.request.user.id)

    # Доступ к view только атворизованным пользователям
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class MyAnswersListView(ListView):
    '''Список ответов пользователя'''
    model = Answer
    context_object_name = 'answers_list'
    template_name = 'answer/list.html'

    def get_queryset(self):
        '''Взять только ответы пользователя'''
        return Answer.objects.filter(user__id=self.request.user.id)

    # Доступ к view только атворизованным пользователям
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@login_required
def create_question_or_answer_view(request):
    '''Страница создания вопросов и ответов'''
    # Хотелось бы применить CreateView, но не придумал, как использовать 
    # CreateView вместе с несколькими моделями

    question_form = CreateQuestionForm()
    answer_form = CreateAnswerForm()
    
    return render(request, 'create.html',
                  {'question_form': question_form,
                   'answer_form': answer_form})


@require_POST
@login_required
def ajax_create_question(request):
    '''Обработка AJAX-запроса на добавление вопроса'''

    if is_ajax(request):
        import json
        data = json.loads(request.body)
        try:
            q = questions.create_question(data.get('text'), 
                                data.get('is_published'), 
                                request.user)
            return JsonResponse(
                {
                    'success': True,
                    'question': {
                        'id': q.id,
                        'text': q.text,
                        'is_published': q.is_published,
                        'created': q.created
                    }
                }
            )
        except ValidationError as err:
            return JsonResponse(
                {
                    'success': False,
                    'error': err.message_dict
                }
            )
    else:
        return HttpResponseForbidden()


@require_POST
@login_required
def ajax_delete_question(request, question_id):
    '''Обработка AJAX-запроса на удаление вопроса'''

    if not is_ajax(request):
        return HttpResponseForbidden()
    try:
        num = questions.delete_users_question(question_id, request.user)
    except Exception as err:
        return JsonResponse({
            'success': False,
            'errors': err
        })
    else:
        return JsonResponse({'success': True, 'deleted_num': num})


@require_POST
@login_required
def ajax_update_question(request, question_id):
    '''Обработка AJAX-запроса на изменение вопроса'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    try:
        import json

        data = json.loads(request.body)
        questions.update_question(id=question_id, **data)
    except Exception as err:
        return JsonResponse({
            'success': False,
            'errors': err
        })
    else:
        return JsonResponse({'success': True})


@require_POST
@login_required
def ajax_create_answer(request):
    '''Обработка AJAX-запроса на добавление ответа пользователем'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    form = CreateAnswerForm(request.POST, request.FILES)
    if form.is_valid():
        answer = answers.create_answer_by_form(request, form)
        answer_thumbnail = answers.get_answer_thumbnail(answer)
        
        return JsonResponse({
            'success': True,
            'answer': {
                'text': answer.text,
                'image_url': answer.image.url,
                'is_published': answer.is_published,
                'thumbnail_url': answer_thumbnail.url
            }
        })
    else:
        return JsonResponse({
            'success': False,
            'errors': form.errors
        })
        

@require_POST
@login_required
def ajax_delete_answer(request, answer_id):
    '''Обработка AJAX-запроса на удаление ответа'''

    if not is_ajax(request):
        return HttpResponseForbidden()
    try:
        num = answers.delete_users_answer(answer_id, request.user)
    except Exception as err:
        return JsonResponse({
            'success': False,
            'errors': err
        })
    else:
        return JsonResponse({'success': True, 'deleted_num': num})


# Колоды
class DeckListView(ListView):
    '''Страница всех колод пользователя'''

    model = Deck
    context_object_name = 'deck_list'
    template_name = 'deck/list.html'

    def get_queryset(self):
        '''Взять только вопросы пользователя'''
        return Deck.objects.filter(user__id=self.request.user.id)

    # Доступ к view только атворизованным пользователям
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@login_required
def create_deck_view(request):
    '''Страница создания колоды'''

    user = request.user
    form = CreateDeckForm()
    questions = user.questions.all()
    answers = user.answers.all()
    return render(request, 'deck/create.html', 
                    {
                        'form': form,
                        'questions': questions,
                        'answers': answers
                    })


@login_required
@require_POST
def ajax_create_deck(request):
    '''Обработка AJAX-запроса на создание колоды'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    success, form, deck = deck_service.create_deck_from_request_with_form(request)

    if success:
        return JsonResponse({
            'success': True,
            'deck': {
                'title': deck.title,
                'text': deck.text,
                'image': deck.image.url if deck.image else None,
                'is_published': deck.is_published,
                'created': deck.created
            },
            'errors': dict(form.errors)
        })
    else:
        return JsonResponse({
            'success': False,
            'deck': None,
            'errors': dict(form.errors)
        })


@login_required
@require_POST
def ajax_delete_deck(request, deck_id):
    '''Обработка AJAX-запроса на удаление колоды'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    try:
        deleted = deck_service.delete_deck(deck_id, request.user)
        return JsonResponse({
            'success': True,
            'deleted_num': deleted
        })
    except Exception as err:
        print(err)
        return JsonResponse({
            'success': False
        })


@login_required
@require_POST
def ajax_update_deck(request, deck_id):
    '''Обработка AJAX-запроса на изменение колоды'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    try:
        deck = deck_service.update_deck(deck_id, request.user, request.POST)
        return JsonResponse({
            'success': True,
            'deck': {
                'id': deck.id,
                'title': deck.title,
                'is_published': deck.is_published,
                'questions': [q['id'] for q in deck.questions.values('id')],
                'answers': [a['id'] for a in deck.answers.values('id')]
            } 
        })
    except Exception as err:
        raise err


# главная
@login_required
def main_page_view(request):
    '''Главная страница, на которой будет отображаться различная информация'''
    pass

game/templates/create.html
{% extends 'base.html' %}

{% block title %}Мои вопросы{% endblock %}

{% block content %}
<main>
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6">
                <h2 class="mb-4">Создать вопрос</h2>
                <form id="questionForm" action="{% url 'game:ajax_create_question' %}" method="post">
                    {% csrf_token %}
                    {% for field in question_form.visible_fields %}
                    {% if field.is_checkbox %}
                    <div class="form-check mb-3">
                        {{field}}
                        <label class="form-check-label" for="{{field.auto_id}}">
                            {{field.label}}
                        </label>
                    </div>
                    {% else %}
                    <div class="mb-3">
                        <label for="{{ field.auto_id }}" class="form-label">{{field.label}}</label>
                        {{field}}
                        <div class="invalid-feedback"></div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-dark">Создать</button>
                </form>
                <ul class="list-group mt-4">
                </ul>
            </div>
            <div class="col-md-6">
                <h2 class="mb-4">Создать ответ</h2>
                <form id="answerForm" action="{% url 'game:ajax_create_answer' %}" method="post"
                    enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in answer_form.visible_fields %}
                    {% if field.is_checkbox %}
                    <div class="form-check mb-3">
                        {{field}}
                        <label class="form-check-label" for="{{field.auto_id}}">
                            {{field.label}}
                        </label>
                    </div>
                    {% else %}
                    <div class="mb-3">
                        <label for="{{ field.auto_id }}" class="form-label">{{field.label}}</label>
                        {{field}}
                        <div class="invalid-feedback"></div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <button type="submit" class="btn btn-dark">Создать</button>
                </form>
                <div class="created-answers mt-4">
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

{% block js_scripts_after %}
<script>
    $(document).ready(function () {

        // создать объект data из формы для отправки через fetch
        function createFormDataObject(form) {
            const formData = new FormData($(form).get(0))
            let data = {}
            formData.forEach((value, name) => {
                data[name] = value
            })
            return data
        }

        // Записать в объект data состояния true/false чекбоксов
        function setCheckboxesInData(data, form) {
            const checkbox = $(form).find('input[type=checkbox]')
            checkbox.each(function (i, el) {
                data[$(el).attr('name')] = $(this).is(':checked')
            })
            return data
        }

        const questionForm = $('#questionForm')
        const answerForm = $('#answerForm')

        questionForm.submit(function (e) {
            e.preventDefault()

            let data = createFormDataObject(this)
            data = setCheckboxesInData(data, this)

            fetch($(this).attr('action'), {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': getCookie('csrftoken'),
                    'X-Requested-With': 'XMLHttpRequest'
                },
                body: JSON.stringify(data)
            })
                .then(response => response.json())
                .then(data => {

                    $(this).find('input, textarea').each(function (i, el) {
                        $(el).removeClass('is-invalid')
                    })

                    if (data.hasOwnProperty('error')) {
                        Object.keys(data.error).forEach(function (key) {
                            const field = questionForm.find(`[name="${key}"]`)
                            field.addClass('is-invalid')
                            field.next('.invalid-feedback').text(data.error[key][0])
                        })
                    }

                    if (data.success) {
                        $(this).get(0).reset()

                        $(this).next('.list-group').append(
                            `<li class="list-group-item" data-q-id="${data.question.id}">${data.question.text}</li>`
                        )
                    }
                })
        })

        answerForm.submit(function (e) {
            e.preventDefault()

            let formdata = new FormData()

            formdata.append('text', $(this).find('[name="text"]').val())
            formdata.append('image', $(this).find('[name="image"]')[0].files[0])
            formdata.append('is_published', $(this).find('[name="is_published"]').is(':checked'))

            fetch($(this).attr('action'), {
                method: 'POST',
                headers: {
                    'X-CSRFToken': getCookie('csrftoken'),
                    'X-Requested-With': 'XMLHttpRequest'
                },
                body: formdata
            })
                .then(req => req.json())
                .then(data => {

                    $(this).find('input, textarea').each(function (i, el) {
                        $(el).removeClass('is-invalid')
                    })

                    if (data.hasOwnProperty('error')) {
                        Object.keys(data.errors).forEach(function (key) {
                            const field = questionForm.find(`[name="${key}"]`)
                            field.addClass('is-invalid')
                            field.next('.invalid-feedback').text(data.error[key][0])
                        })
                    }

                    if (data.success) {
                        $(this).get(0).reset()

                        $(this).next('.created-answers').append(
                            `<div class="created-answer" 
                                data-q-id="${data.answer.id}"
                            >
                                <img class="img-thumbnail" src="${data.answer.thumbnail_url}" />
                            </div>`
                        )
                    }

                })
        })

    })
</script>
{% endblock %}