account/urls.py
from django import urls
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('registration/', views.account_register_new_user, name='registration'),
    path('profile/', views.account_profile, name='self_account_profile'),
    path('profile/<int:profile_id>/', views.account_profile, name='account_profile'),
    path('profile/photo/change/', views.profile_change_photo, name='profile_change_photo'),
    path('ajax-search-profiles', views.ajax_search_profiles, name='ajax_search_profiles'),
    path('ajax-invite-friends/', views.ajax_invite_friends, name='ajax_invite_friends'),
    path('notifications/', views.NotificationListView.as_view(), name='notification_list'),
    path('ajax-notifications-set-viewed/', views.ajax_notifications_set_viewed, name='ajax_notifications_set_viewed'),
    path('ajax-choose-friend-inviting/', views.ajax_accept_or_reject_friend_inviting, name='ajax_accept_or_reject_friend_inviting'),
]

game/urls.py
from django.urls import path
from . import views


app_name = 'game'

urlpatterns = [
    path('my-questions/', views.MyQuestionListView.as_view(), name='my_questions'),
    path('my-answers/', views.MyAnswersListView.as_view(), name='my_answers'),
    path('create-question-or-answer/', views.create_question_or_answer_view, 
                                       name='create_question_or_answer'),
    path('ajax-create-question/', views.ajax_create_question, name='ajax_create_question'),
    path('ajax-delete-question/<int:question_id>', views.ajax_delete_question, name='ajax_delete_question'),
    path('ajax-update-question/<int:question_id>', views.ajax_update_question, name='ajax_update_question'),
    path('ajax-create-answer/', views.ajax_create_answer, name='ajax_create_answer'),
    path('ajax-delete-answer/<int:answer_id>', views.ajax_delete_answer, name='ajax_delete_answer'),

    # колода
    path('create-deck/', views.create_deck_view, name='create_deck'),
    path('my-decks/', views.DeckListView.as_view(), name='my_decks'),
    path('ajax-create-deck/', views.ajax_create_deck, name='ajax_create_deck'),
    path('ajax-delete-deck/<int:deck_id>', views.ajax_delete_deck, name='ajax_delete_deck'),
    path('ajax-update-deck/<int:deck_id>', views.ajax_update_deck, name='ajax_update_deck'),

    # главная
    # path('',)

    # игра
    # path('play/'),
    # path('create-game/', views.create_game_view, name='create_game'),
]

memotron/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('game.urls', namespace='game')),
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls'))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField('auth.user', on_delete=models.CASCADE,
                                related_name='profile')
    photo = models.ImageField(
                            verbose_name='Аватар профиля', 
                            upload_to='profile/%Y/%m/%d/',
                            null=True,
                            blank=True)
    birth_date = models.DateTimeField('Дата рождения', null=True, blank=True)
    friends = models.ManyToManyField('self', through='Following')
    registered = models.DateTimeField('Зарегистрирован', auto_now_add=True)
    extra_id = models.CharField('Идентификатор', max_length=4, db_index=True)

    def get_absolute_url(self):
        return reverse('account:account_profile', args=[self.id])


class Following(models.Model):
    '''Класс m2m для системы подписок пользователей друг на друга'''

    friend1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friend1')
    friend2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friend2')
    date = models.DateTimeField('Начало дружбы', auto_now_add=True)


class Notification(models.Model):
    '''Модель уведомлений'''

    # Пользователь, которому пришло уведомление
    user = models.ForeignKey('auth.user', 
                            on_delete=models.CASCADE, 
                            related_name='income_notifications')
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    title = models.CharField('Название', max_length=200)
    content = models.TextField('Содержание', null=True, blank=True)
    typeof = models.CharField('Тип уведомления', max_length=100)
    from_user = models.ForeignKey('auth.user', 
                                    on_delete=models.SET_NULL, 
                                    related_name='outcome_notifications',
                                    null=True)
    is_viewed = models.BooleanField('Просмотрено', default=False)
    is_visible = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

account/forms.py
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


class AccountLoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': ''
            }
        ),
        label='Логин'
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': ''
            }
        )
    )


class AccountRegistrationForm(forms.ModelForm):
    '''Форма регистрации пользователя'''

    # Поля
    password1 = forms.CharField(label='Пароль', 
                                widget=forms.PasswordInput())
    password2 = forms.CharField(label='Повторите пароль', 
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        self['username'].label = 'Логин'

    def is_valid(self):
         result = super().is_valid()
         # loop on *all* fields if key '__all__' found else only on errors:
         for x in (self.fields if '__all__' in self.errors else self.errors):
             attrs = self.fields[x].widget.attrs
             attrs.update({'class': attrs.get('class', '') + ' is-invalid'})
         return result

    # Проверить, существует ли пользователь с таким именем
    def clean_username(self):
        username = self.cleaned_data['username']

        if User.objects.filter(username=username).exists():
            raise ValidationError('Такое имя уже существует')

        return self.cleaned_data['username']

    def clean_password2(self):
        password2 = self.cleaned_data['password2']

        if password2 != self.cleaned_data['password1']:
            raise ValidationError('Пароли не совпадают')

        return password2


class UploadFileForm(forms.Form):
    '''Базовая форма для загрузки файла'''
    filename = forms.CharField(max_length=50)
    file = forms.FileField()

account/services/utils/forms.py
'''Модуль для работы с формами'''


def process_form_fields(form, checked=False, textarea_rows=3):
    '''Добавить классы bootstrap для полей формы и изменить виджеты.
    Если checked=True, все чекбоксы будут отмечены. По умолчанию False.'''

    for visible in form.visible_fields():
        if visible.field.widget.__class__.__name__ == 'CheckboxInput':
            visible.is_checkbox = True
            visible.field.widget.attrs['class'] = 'form-check-input'
            if checked:
                visible.field.widget.attrs['checked'] = True
        else:
            visible.field.widget.attrs['class'] = 'form-control'

            if visible.field.widget.__class__.__name__ == 'Textarea':
                visible.field.widget.attrs['rows'] = str(textarea_rows)

account/views.py
import json

from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.views.decorators.http import require_POST, require_GET
from django.shortcuts import get_object_or_404
from django.http import HttpResponseForbidden

from .forms import AccountLoginForm, AccountRegistrationForm
from .models import Profile, Notification
from .services.registration import register_new_user
from .services import profile_serv
from .services.utils.ajax import is_ajax


class LoginView(auth_views.LoginView):
    '''Страница входа'''
    authentication_form = AccountLoginForm


def account_register_new_user(request):
    '''Страница регистрации'''
    if request.method == 'POST':
        form = AccountRegistrationForm(request.POST)
        success = register_new_user(form)
        if success:
            return redirect('account:self_account_profile')
        else:
            return render(request, 'account/registration.html', {'form': form})
    else:
        # Вернуть шаблон страницы
        form = AccountRegistrationForm()
    return render(request, 'account/registration.html', {'form': form})


@login_required
def account_profile(request, profile_id=None):
    '''Страница профиля'''
    if not profile_id:
        profile = get_object_or_404(Profile, id=request.user.profile.id)
        return render(request, 'account/profile/detail.html',
                            {'profile': profile})
    profile = get_object_or_404(Profile, id=profile_id)
    return render(request, 'account/profile/detail.html',
                            {'profile': profile})


@require_POST
def profile_change_photo(request):
    '''Изменение фото профиля из ajax-запроса'''
    if is_ajax(request):
        success, profile = profile_serv.change_profile_photo(request)
        if success:
            return JsonResponse({'url': profile.photo.url})
        else:
            return JsonResponse({'error': 'Что-то пошло не так'})
    else:
        return HttpResponseForbidden()


@require_GET
@login_required
def ajax_search_profiles(request):
    '''Поиск пользователей через AJAX'''
    
    if not is_ajax(request):
        return HttpResponseForbidden()

    data = profile_serv.search_profiles(request.user, request.GET)

    return JsonResponse(data)



@require_POST
@login_required
def ajax_invite_friends(request):
    '''Приглашение в друзья через AJAX'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    user_ids = [int(id) for id in request.POST.get('user_ids').split(',')]
    profile_serv.invite_friends(request.user, user_ids)

    return JsonResponse({
        'success': True
    })


class NotificationListView(ListView):
    '''Список уведомлений'''

    context_object_name = 'notifications'
    template_name = 'notifictation/list.html'

    def get_queryset(self):
        return Notification.objects.filter(user=self.request.user, is_visible=True)


@login_required
@require_POST
def ajax_notifications_set_viewed(request):
    '''Сделать уведомления просмотренными'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    notification_ids = json.loads(request.body.decode('utf-8'))
    profile_serv.set_notifications_viewed(notification_ids.get('notifications'))
    return JsonResponse({'success': True})


@login_required
@require_POST
def ajax_accept_or_reject_friend_inviting(request):
    '''Принять запрос в друзья'''

    if not is_ajax(request):
        return HttpResponseForbidden()

    data = json.loads(request.body.decode('utf-8'))

    if data.get('accepted'):
        profile_serv.accept_friend_inviting(data.get('user'), request.user)
    else:
        profile_serv.reject_friend_inviting(data.get('user'), request.user)

    Notification.objects.filter(id=data.get('notification_id')).update(is_visible=False)

    return JsonResponse({'success': True})

account/templates/includes/header.html
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Memotron</a>
            {% if request.user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav flex-grow-1 mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Посмотреть
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a 
                                    class="dropdown-item" 
                                    href="{% url 'game:my_questions' %}"
                                >
                                    Мои вопросы
                                </a>
                            </li>
                            <li>
                                <a 
                                    href="{% url 'game:my_answers' %}" 
                                    class="dropdown-item"
                                >
                                    Мои ответы
                                </a>
                            </li>
                            <li>
                                <a 
                                    href="{% url 'game:my_decks' %}" 
                                    class="dropdown-item"
                                >
                                    Мои колоды
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Создать
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a 
                                    class="dropdown-item" 
                                    href="{% url 'game:create_question_or_answer' %}"
                                >
                                    Вопрос или ответ
                                </a>
                            </li>
                            <li>
                                <a 
                                    href="{% url 'game:create_deck' %}" 
                                    class="dropdown-item"
                                >
                                    Колоду
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="btn btn-success ms-2">Играть</a>
                    </li>
                    <li class="nav-item">
                        <a 
                            href="#"
                            class="btn btn-info ms-2"
                            data-bs-target="#createGame"
                            data-bs-toggle="modal"
                        >Создать игру</a>
                    </li>
                    <!-- <form class="d-flex ms-auto">
                        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Искать</button>
                    </form> -->
                    <li class="nav-item dropdown ms-auto">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            {{ request.user.first_name }}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li>
                                <a 
                                    class="dropdown-item" 
                                    href="{% url 'account:self_account_profile' %}"
                                >
                                    Профиль
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'account:notification_list' %}">
                                    Уведомления
                                    {% if new_notifications.count %}
                                        <span class="badge bg-warning text-dark">    
                                            {{new_notifications.count}}
                                        </span>
                                    {% endif %}
                                </a>
                            </li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account:logout' %}">Выйти</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            {% endif %}
        </div>
    </nav>
</header>